feat: create auth api and add prisma to the project
PurpleSchool/hackaton-finance-2 pull request #1
Opened 2023-06-08 18:20 UTC by rejth

1. Добавил бойлерплет с express, prisma и inversify.
2. Создал 3 эндпоинта: /register, /login, /info для сущности User.
3. Инициализировал Prsima в проекте, пока что на базе sqlite для быстрого старта и проверки Auth API.

2023-06-10 04:33 UTC, ilshatufa requested changes
Привет, отличная работа)
Хочу попросить составить тест план, краткий, что запустить, что нажать, чтобы проверить функционал авторизации

2023-06-10 09:40 UTC, rejth commented
`nx serve server`
Дальше берешь любой HTTP Client (Postman, Insomnia) и отправляешь запросы:
1. `POST http://localhost:3333/auth/register`, body: `{
	"email": "test1@mail.ru",
	"password": "12345",
	"name": "Test1"
}`
2. `POST http://localhost:3333/auth/login`, body: `{
	"email": "test1@mail.ru",
	"password": "12345"
}` - скопировать accessToken в ответе
3. `GET http://localhost:3333/auth/info`, `Bearer access token from POST /login endpoint`

2023-06-12 16:32 UTC, ilshatufa commented
Я провел блекбокс тестирование, не залезал сильно в код, так как пока мало что понимаю((( 

Накидал своих мыслей

Что бросается в глаза - так это отсутствие описание контрактов, обычно сначала пишут описание методов апи, (не обязательно сваггер, можно простой документик) а потом уже реализуют. Иначе не понятно что проверять, все ли соответствует тому что задумывалось. 

Хорошим тоном считается разработка по TDD - сначала интеграционные тесты а потом уже апи. По опыту - отсекает 90% ошибок. Но это так, лирика))) 

Разработка в соответствии c описанию методов отсечет такие ошибки - как в одном методе ошибка передается в поле err, в другом в поле error. 
![image](https://github.com/PurpleSchool/hackaton-finance-2/assets/12667433/bd53ebb4-113a-491b-9dd3-3e5197693697)
![image](https://github.com/PurpleSchool/hackaton-finance-2/assets/12667433/109df10a-ee8c-47ff-a2cd-5a8c02360677)

Так как мы пишем апи не для интеграций, а для фронта, то предлагаю делать его минималистичным, то есть передавать только те данные, которые заведомо нужны. 

Обработку ошибок, как предложение, - можно составить список ошибок, и присвоить им коды, и на фронт передавать именно код ошибки а не сообщение. На фронте же нужен будет словарь с текстами ошибок на разных языках чтобы сразу подставлять успешный перевод в соответствии с языком

Так же желательно сделать глобальную обработку ошибок, чтобы бек не падал, а что то отправлял пользователю.

register
После успешной регистрации можно просто отдать status: success 
А при валидации что то типа errorCode: wrongEmail, errorCode: wrongPassword

login 
падает при регистрации с верными кредами)
![image](https://github.com/PurpleSchool/hackaton-finance-2/assets/12667433/2201ffba-facf-4c31-af10-c6d8fe75db5b)

До info так и не добрался, так как не смог залогиниться

2023-06-12 16:33 UTC, ilshatufa commented
Предложения на подумать
Добавить в ссылку как часть пути  /api/ чтобы не было случайных пересечений с другими запросами (http://localhost:3333/api/auth/register)
Добавить версионность (http://localhost:3333/api/v1/auth/register)

2023-06-13 14:03 UTC, merged